### ISSUE TITLE
Unable to craft crystal

### ISSUE THREAD

**Issue by NikitaDarkstar** [n643064/HeartCrystals#1]
When filling up the crafting grid with shards I'm not given the option to craft a crystal. I'm on NeoForge, 1.21.1

![2024-11-18_02 36 41](https://github.com/user-attachments/assets/e0e56960-f0d1-42ff-9f77-2663778d23ae)

**Comment by n643064** [comment]
[fixed](https://modrinth.com/mod/heart-crystals/version/1.0.1-1.21)
